{
  "hash": "fc7a267e61114781badc9794e3061e8e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Beyond DAU: How to Measure User Retention with Survival Analysis\"\ndate: \"2026-08-23\"\ndescription: \"Use survival analysis to measure whether a product feature creates durable engagement beyond a short-lived DAU spike.\"\nimage: preview.png\nimage-alt: \"Timelines comparing the engagement of a habitual user and a user who bounced\"\nimage-width: \"1344\"\nimage-height: \"960\"\nopen-graph: true\ntwitter-card: true\ncategories:\n  - r\nformat: html\nexecute:\n  eval: true\n---\n\n# The Team's Nightmare: Spike and Baseline\n\nHere's an all-too-common scenario: your team makes a heroic effort to implement\na new product feature, finally launches it, and everyone celebrates the initial\nburst of daily usage---until the graph flattens and returns to its pre-launch\nbaseline. You have launched a dud.\n\nWhat makes this scenario particularly disturbing is that a proper launch\nexperiment, in which we'd ramp up feature availability and compare the treatment\ngroup with a control group, would probably have registered a positive impact on\ndaily usage, fueled mostly by hype and word-of-mouth. But once the initial\nexcitement is over, and users realize they didn't need the new feature, it's back\nto baseline.\n\nGetting a user to click a shiny new button once is easy. The true test of a\nfeature's value---of its *utility* to the user---is whether it contributes to\nuser retention. I'll go so far as to claim that the best proxy for *any*\nproduct's quality is user retention.\n\nHow do we measure user retention? Certainly not by measuring week-over-week\nretention. I'll explain.\n\n# The Week-over-Week Retention Siren Song\n\nWhen measuring retention, it is incredibly tempting to reach for simple binary\noutcomes. We ask questions like, *\"On average, what proportion of users return within 7 days after using the product?\"*\n\n[DAU](https://en.wikipedia.org/wiki/Active_users) has the same limitation at the aggregate level: it tells us how much\nactivity happened, but not whether the launch created durable habits among\nindividual users. A one-off spike and sustained retention can produce similar\nshort-term DAU numbers.\n\nAlthough simple to query and easy to explain, these metrics are inefficient and\ncan lead to misleading insights:\n\n1.  **Arbitrary Time Horizons**: Why 7 days? Why not 30 days? Fixed windows are\narbitrary. Suppose your users use the product once every week, and the feature\nmakes them come back twice a week. A metric like week-over-week retention would\nbe blind to such a dramatic impact.\n2.  **Masking Acceleration**: A fantastic feature might do more than merely\nbring users back; it might bring them back *faster*. A fixed-window binary\nmetric only asks *if* they returned, not *how much sooner*.\n3.  **Confounding Activation with Retention**: If your UI change successfully\nactivates a massive wave of new users, a simple population-wide return metric\ncan be heavily skewed. We need a framework that isolates the effect on initial\nactivation from the effect on sustained repeat usage among those already\nactivated.\n\nI claim that there is a statistical tool that addresses all three problems. It\nis [*survival analysis*](https://en.wikipedia.org/wiki/Survival_analysis),\napplied to [recurrent events](https://en.wikipedia.org/wiki/Recurrent_event_analysis).\nBut let's first look at an example.\n\n# Meet Alice and Bob\n\nLet's look at the timelines of two hypothetical users who enroll in our\nexperiment on different calendar days. We analyze both users on calendar day 14,\nso they are [censored](https://en.wikipedia.org/wiki/Censoring_%28statistics%29)\nat the same calendar time but have different amounts of follow-up.\n\nHere's what their timelines might look like:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\nHere's the story told by this plot:\n\n-   **Alice** enrolls on Day 1, tries the feature on Day 3, and triggers\nmultiple repeat events before she is censored on the analysis date, Day 14.\n-   **Bob** enrolls on Day 4, gets exposed, but never triggers a single event\nbefore being censored on that same analysis date.\n\nThe key insight here is that we're going to model two different kinds of\ngap times:\n\n1. The time until the first use of the product (at most one gap time per user)\n2. The time between subsequent uses of the product (zero or more such intervals\nper user)\n\nThe simple aggregate metrics discussed above struggle with Alice's repeated\nevents and do not handle Bob's right-censoring correctly. Simply excluding users\nlike Bob from the analysis is a serious mistake.\n\n# Using the Cox Model for Product Usage\n\nTo analyze these timelines rigorously, we use the **[Cox proportional hazards\nmodel](https://en.wikipedia.org/wiki/Proportional_hazards_model)** for recurrent\nevents.\n\nIf you took a statistics class, you might remember survival analysis being used\nin medical research where an \"event\" means failure or death.\n\n(Whether we like it or not, biostatisticians got there first and named the\nconcepts, which is why terms such as \"[hazard\nratio](https://en.wikipedia.org/wiki/Hazard_ratio)\" and \"survival curve\" can sound\ncounterintuitive in a product context. I always need a couple of minutes to\nexplain this to a non-technical audience.)\n\nFor product usage, we define an **event** as *any day on which the user used the\nproduct at least once*.\n\n## Interpreting Survival Analysis Outcomes\n\nThe [hazard rate](https://en.wikipedia.org/wiki/Failure_rate#Hazard_rate) is the\nfundamental quantity in a survival model. When we compare two treatments, our\nkey metric is their hazard ratio. It sounds like a terrible thing, but in this\nsetting it is exactly what we want to be high.\n\n-   **The Hazard Rate ($h(t)$)**: Think of this as a user's *instantaneous momentum*—the instantaneous rate of engagement at time $t$, given that they haven't engaged yet in the current interval.\n-   **The Hazard Ratio (HR)**: This is our ultimate success metric. It compares the engagement momentum of our treatment group to the control group ($HR = h_{treatment}(t) / h_{control}(t)$).\n    -   **$HR > 1$**: The treatment accelerates usage. Users return faster and more frequently. **This is what we want.**\n    -   **$HR = 1$**: Flat impact.\n    -   **$HR < 1$**: The treatment slows down engagement.\n\n## Key Model Assumptions\n\nWhen applying this model, we rely on four fundamental assumptions:\n\n1.  **Proportional Hazards**: We assume that the hazard ratio is constant over time. If our shiny new UI doubles a user's instantaneous return rate on Day 2, it should also roughly double it on Day 8.\n2.  **[Non-informative Censoring](https://en.wikipedia.org/wiki/Censoring_%28statistics%29#Types)**: We assume that users being censored (their window ending) tells us nothing about their underlying habits. I find this hard to wrap my head\naround, but it mainly means that we run the analysis at a date that has nothing\nto do with whether we're still waiting for some users to act. A fixed\nadministrative cutoff makes this assumption plausible, provided that the cutoff\nis unrelated to the users' underlying propensity to return.\n3.  **Independence Across Clusters**: While Alice's repeat events are obviously correlated with each other, we assume Alice's behavior is completely independent of Bob's.\n4.  **[Shared Frailty](https://en.wikipedia.org/wiki/Recurrent_event_analysis#Frailty_models)**:\nWe assume that each user's unobserved propensity to engage is constant over the\nobservation window and follows a [gamma\ndistribution](https://en.wikipedia.org/wiki/Gamma_distribution) across users.\n\n# A Simulation\n\nLet's test this model by simulating a reasonably realistic dataset. We will\ngenerate 2,000 users who experience varying numbers of repeat events within a\nfixed 10-day window. Events occur on a daily grid, so each user can have at most\none event per day.\n\nTo make it more realistic, we inject a **gamma frailty** (a random effect) per\nuser. This simulates the fact that some people are inherently \"power users\"\nwhile others are inherently casual, inducing true within-user correlation.\n\nHere is the complete simulation code, including the model fitting:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(survival)\n\n# Set seed for reproducibility\nset.seed(123)\n\nn_users <- 2000\nobs_window <- 10 # 10-day follow-up window per user\n\n# 1. Simulate Treatment Allocation and Inherent Frailty\n# A gamma distribution with mean 1 centers our \"average\" user\nuser_frailty <- rgamma(n_users, shape = 2, rate = 2)\nusers <- data.frame(\n  user_id = 1:n_users,\n  treatment = rbinom(n_users, 1, 0.5),\n  frailty = user_frailty\n)\n\nsimulated_data <- list()\n\n# 2. Generate timelines using a gap-time formulation\nfor (i in 1:n_users) {\n  u <- users[i, ]\n  current_time <- 0\n  event_count <- 0\n\n  while (current_time < obs_window) {\n    is_first <- (event_count == 0)\n\n    # Baseline rates: harder to activate initially, easier to trigger repeat usage\n    base_rate <- if (is_first) 0.05 else 0.15\n\n    # Let's say our treatment is amazing: doubles activation (HR=2), triples repeat usage (HR=3)\n    hr <- if (u$treatment == 1) {\n      if (is_first) 2.0 else 3.0\n    } else {\n      1.0\n    }\n\n    # The latent daily rate combines baseline, treatment boost, and personal frailty\n    rate <- base_rate * hr * u$frailty\n\n    # Geometric waiting times are whole days and are always at least one,\n    # ensuring at most one event per user per day.\n    daily_event_probability <- 1 - exp(-rate)\n    t_next <- rgeom(1, prob = daily_event_probability) + 1\n\n    if (current_time + t_next <= obs_window) {\n      # Event occurs inside the window! Reset the gap-time clock.\n      event_count <- event_count + 1\n      current_time <- current_time + t_next\n\n      simulated_data[[length(simulated_data) + 1]] <- data.frame(\n        user_id = u$user_id,\n        treatment = u$treatment,\n        is_first_event = is_first,\n        time = t_next, # Whole days since the last event\n        event = 1\n      )\n    } else {\n      # Window ends before the next event occurs. Censor the remaining time.\n      t_censored <- obs_window - current_time\n      simulated_data[[length(simulated_data) + 1]] <- data.frame(\n        user_id = u$user_id,\n        treatment = u$treatment,\n        is_first_event = is_first,\n        time = t_censored,\n        event = 0 # Censored observation\n      )\n      break\n    }\n  }\n}\n\ndf <- do.call(rbind, simulated_data)\n\n# 3. Fit a Cox model with shared gamma frailty\n# strata(...) gives activation and repeat usage separate baseline hazards.\nmodel <- coxph(\n  Surv(time, event) ~ treatment * strata(is_first_event) +\n    frailty(user_id, distribution = \"gamma\"),\n  data = df\n)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(time, event) ~ treatment * strata(is_first_event) + \n    frailty(user_id, distribution = \"gamma\"), data = df)\n\n  n= 4137, number of events= 2439 \n\n                          coef    se(coef) se2     Chisq  DF    p      \ntreatment                  1.0732 0.0760   0.06576 199.37   1.0 2.9e-45\nfrailty(user_id, distribu                          927.77 569.1 1.2e-19\ntreatment:strata(is_first -0.4691 0.1034   0.09505  20.57   1.0 5.7e-06\n\n                                                    exp(coef) exp(-coef)\ntreatment                                              2.9246     0.3419\ntreatment:strata(is_first_event)is_first_event=TRUE    0.6256     1.5985\n                                                    lower .95 upper .95\ntreatment                                              2.5198    3.3944\ntreatment:strata(is_first_event)is_first_event=TRUE    0.5108    0.7661\n\nIterations: 6 outer, 45 Newton-Raphson\n     Variance of random effect= 0.402791   I-likelihood = -17064.6 \nDegrees of freedom for terms=   0.7 569.1   0.8 \nConcordance= 0.786  (se = 0.005 )\nLikelihood ratio test= 1481  on 570.6 df,   p=<2e-16\n```\n\n\n:::\n:::\n\n\n# Reading the Model Output\n\nThe shared-frailty term explicitly models each user's persistent, unobserved\npropensity to return. The resulting treatment effects are conditional on that\nfrailty: they compare treated and control users with the same latent propensity\nfor engagement. This differs from a [marginal\nmodel](https://en.wikipedia.org/wiki/Recurrent_event_analysis#Marginal_means/rates_model)\nwith [cluster-robust standard\nerrors](https://en.wikipedia.org/wiki/Clustered_standard_errors), which adjusts\nthe uncertainty for repeated observations without explicitly modeling the\nuser-level heterogeneity.\n\nFor product decisions, this conditional interpretation answers an important\nquestion: *\"Does the treatment get otherwise similar users to come back to the\nproduct more frequently?\"*\n\nThe `coef` column is additive on the log-hazard scale. Exponentiating a\ncoefficient converts it into a hazard-ratio multiplier. Because\n`is_first_event = FALSE` is the reference stratum, the `treatment` coefficient\ndescribes repeat usage:\n\n$$\nHR_{\\text{repeat}} = \\exp(\\beta_{\\text{treatment}}) \\approx 2.925\n$$\n\nThis is close to the simulated repeat-use hazard ratio of 3.0.\n\nThe [interaction term](https://en.wikipedia.org/wiki/Interaction_%28statistics%29)\ndoes not represent the first-use hazard ratio by itself. It represents the ratio\nbetween the first-use and repeat-use hazard ratios. Its exponentiated estimate\nis about 0.626, reasonably close to the simulated target of $2/3 \\approx 0.667$.\nTo recover the first-use effect, add the two coefficients on the log-hazard\nscale---or, equivalently, multiply their exponentiated values:\n\n$$\nHR_{\\text{first}} = \\exp(\\beta_{\\text{treatment}} + \\beta_{\\text{interaction}})\n           = 2.925 \\times 0.626\n           \\approx 1.83\n$$\n\nThis is close to the simulated first-use hazard ratio of 2.0. The estimates do\nnot reproduce the inputs exactly because they come from a finite random sample.\nFinally, the `frailty(...)` line in the summary is not another treatment\ncoefficient; it describes the contribution of the shared user-level random\neffect.\n\n# In Real Life\n\nI presented this method at my day job, where it was accepted as a valid way to\nmeasure user retention. It will now be included in the playbook for future\nlaunches.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}