project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://blog.davidlindelof.com
  title: "David's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: bluesky
        href: https://bsky.app/
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto
  eval: false


