project:
  type: website
  resources:
    - CNAME

website:
  description: "A blog built with Quarto"
  site-url: https://blog.davidlindelof.com
  title: "David's blog"
  navbar:
    right:
      - about.qmd
      - text: R-bloggers
        href: https://www.r-bloggers.com/
      - icon: github
        href: https://github.com/
      - icon: bluesky
        href: https://bsky.app/
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto
  eval: false
