project:
  type: website
  resources:
    - CNAME

website:
  description: "Notes on statistics, data science, software engineering, and scientific computing."
  favicon: favicon.svg
  site-url: https://blog.davidlindelof.com
  open-graph: true
  twitter-card: true
  plausible-analytics:
    path: _plausible_snippet.html
  title: "David's blog"
  navbar:
    right:
      - about.qmd
      - text: R-bloggers
        href: https://www.r-bloggers.com/
      - icon: github
        href: https://github.com/dlindelof
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/dlindelof
        aria-label: Twitter
      - icon: linkedin
        href: https://www.linkedin.com/in/lindelof/
        aria-label: LinkedIn
      - icon: rss
        href: index.xml
        aria-label: RSS
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto
